yacw-team/yacw-frontend

- src/api/translate/req.ts
- src/api/translate/res.ts
- src/api/translate/translate.ts
- src/router/index.ts
- src/views/Translate/TranslateView.vue
- src/views/Translate/list/emotion.ts
- src/views/Translate/list/fromLang.ts
- src/views/Translate/list/style.ts
- src/views/Translate/list/toLang.ts
- vite.config.ts
Add from&to language list, emotion&style list;
Add translate view logic.
> Merge: Translate View Logic

- src/views/Translate/TranslateView.vue
1. Change textarea style;
2. change toLang default to English;
3. add reset option button.
> Update: Translate View

- src/components/PromptShop.vue
> Fix: #60 Prompt 商店排版 CSS 修复

- components.d.ts
- package-lock.json
- package.json
- src/views/Translate/TranslateView.vue
- yarn.lock
修复了交换文本框文字按钮点击范围过大的bug
Issue #64
> Fix: 翻译界面 交换文本框文字按钮点击范围过大 #64

- src/views/Chat/ChatView.vue
- src/views/HomePage/HomePage.vue
> fixed #42 输入 Key 检查其可用性

- src/views/Chat/components/PromptLibrary.vue
Fix Issue：#74 Bug: 从后端获取userPrompt
> Fix Issue：#74 Bug: 从后端获取userPrompt

- src/views/Chat/ChatView.vue
- yarn.lock
> Update: 回车发送消息 #50

- src/views/Chat/components/ChatMessage.vue
- src/views/Chat/components/CreatePersonality.vue
- src/views/Chat/components/PromptLibrary.vue
Fix Issue #58 ，#54 Feat:完善用户创建Prompt功能，一键复制对话内容
> Fix Issues #58 #54  Feat:完善用户创建Prompt功能，一键复制对话内容

- src/api/chat/chat.ts
- src/api/chat/req.ts
- src/api/chat/res.ts
- src/components/Loading.vue
- src/router/index.ts
- src/views/Chat/ChatView.vue
> Feat: #46 聊天界面 直接发送对话时新建对话

- src/utils/modelIdToName.ts
- src/views/HomePage/HomePage.vue
- src/views/HomePage/components/ModelSelectCard.vue
> Update: #41 选择模型后改变按钮及弹窗样式

- src/views/Chat/ChatView.vue
- src/views/Chat/components/ChatMessage.vue
- src/views/HomePage/HomePage.vue
> fix #56 #89

- src/views/Game/components/TopBarMenu.vue
issue https://github.com/yacw-team/yacw-frontend/issues/94  New: 增加游戏页面的顶栏 
issue https://github.com/yacw-team/yacw-frontend/issues/96  New: 用户点击帮助展示游戏玩法
> New: 增加游戏页面的顶栏 #94 and New: 用户点击帮助展示游戏玩法 #96

- src/views/HomePage/HomePage.vue
> Fix: 更换 Key 弹窗填充文字内容位置错误

- src/views/HomePage/HomePage.vue
> Update: #108 添加 apikey 验证时候的加载反馈

- src/components/PromptShop.vue
- src/components/getAllStory.vue
> Fix Issue： #107 New: 剧本选择添加开始按钮

- src/api/home/home.ts
- src/api/home/req.ts
- src/views/HomePage/HomePage.vue
> Enhance: 提取 HomePage Axios 函数 #115

- src/components/SideBar.vue
> Enhance: 删除侧边栏中的情感咨询按钮 #98

- src/main.ts
- src/views/Chat/components/PromptLibrary.vue
- src/views/Translate/TranslateView.vue
Fix several errors:
Issue #109 Prompt 商店按钮大小错误
Issue #120 翻译页面交换内容按钮 hover 范围过大
Issue #125 ElMessage 样式错误
> Fix Error #109 #125 #120

- src/api/chat/prompt/prompt.ts
- src/api/chat/prompt/req.ts
- src/views/Chat/components/PromptLibrary.vue
Fix #134,#135,#136    逆序遍历prompt， 删除 myprompt，显示用户prompt立刻更新
> Fix #134,#135,#136    逆序遍历prompt， 删除 myprompt，显示用户prompt立刻更新

- src/views/Chat/ChatView.vue
> Fix: #90 聊天对话过多页面不断拉长

- src/views/Translate/TranslateView.vue
> Fix: #144 翻译界面拉长后输入框与按钮错位

- src/views/Game/bookTest.vue
- src/views/Game/gamePage.vue
> Enhance: #150 游戏界面黑暗模式字体样式

- src/components/SideBar.vue
Issue https://github.com/yacw-team/yacw-frontend/issues/39  Feat: 支持更换后端 URL
> #39 Feat: 支持更换后端 URL 
